ealier there was not documented limit of primes leading to called `Option::unwrap()` on a `None` value
because of prime was not found it was not possible to unwrap

This problem was fixed:

thread 'main' panicked at /home/daniel/exp/compact/src/compact_hash_map.rs:466:54:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: compact::compact_hash_map::OpenAddressingMap<K,V,A>::with_capacity
   5: chashmap::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

impact on performence is neglectible